# Generated by Django 5.2.8 on 2025-12-01 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('nombre', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('anio', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta_img', models.ImageField(blank=True, null=True, upload_to='capitulos/')),
                ('romance', models.BooleanField(default=False)),
                ('risas', models.BooleanField(default=False)),
                ('lagrimas', models.BooleanField(default=False)),
                ('violencia', models.BooleanField(default=False)),
                ('peligro', models.BooleanField(default=False)),
                ('armas', models.BooleanField(default=False)),
                ('sexo', models.BooleanField(default=False)),
                ('eventos', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('nombre', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('ruta_img', models.ImageField(blank=True, null=True, upload_to='diarios/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapituloImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('ruta', models.ImageField(upload_to='capitulos/extras/')),
                ('tag', models.CharField(max_length=100)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.capitulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapituloPista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='core.capitulo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CapituloSlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('ruta', models.ImageField(upload_to='capitulos/slaps/')),
                ('nivel', models.IntegerField(default=0)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slaps', to='core.capitulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ruta_img', models.ImageField(blank=True, null=True, upload_to='personajes/')),
                ('prioridad', models.IntegerField(default=0)),
                ('capitulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes', to='core.capitulo')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to='core.diario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('ruta_img', models.ImageField(blank=True, null=True, upload_to='mensajes/')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('fecha_simulada', models.DateField(blank=True, null=True)),
                ('hora_simulada', models.TimeField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversacion')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='core.personaje')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='conversacion',
            name='personajes',
            field=models.ManyToManyField(related_name='conversaciones', to='core.personaje'),
        ),
        migrations.CreateModel(
            name='Tomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('nombre', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('ruta_img', models.ImageField(blank=True, null=True, upload_to='tomos/')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomos', to='core.diario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='personaje',
            name='tomo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes', to='core.tomo'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='tomo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='core.tomo'),
        ),
    ]
