# Generated by Django 5.2.8 on 2025-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diario',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='tomo',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='diario',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tomo',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
