# Generated by Django 5.2.8 on 2025-12-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instagramperfil_presentacion_recuerdoleticia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoUmbralCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100)),
                ('itemid', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='mercadoumbral/compras/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MercadoUmbralNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
