# Generated by Django 5.2.8 on 2025-12-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mercadoumbralcompra_mercadoumbralnoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoUmbralCyborg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('codigo', models.CharField(max_length=100)),
                ('humano', models.BooleanField(default=False)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('material_construccion', models.CharField(max_length=255)),
                ('densidad_cabello', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piel_sintetica', models.BooleanField(default=False)),
                ('chip_version', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='mercadoumbral/cyborgs/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MercadoUmbralHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('codigo', models.CharField(max_length=100)),
                ('humano', models.BooleanField(default=True)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('buscada', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='mercadoumbral/humanos/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
