# Generated by Django 5.2.8 on 2025-12-01 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mercadoumbralcyborg_mercadoumbralhumano'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoUmbralHumanoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('imagen', models.ImageField(upload_to='mercadoumbral/humanos/extras/')),
                ('orden', models.IntegerField(default=0)),
                ('humano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.mercadoumbralhumano')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
