# Generated by Django 5.2.8 on 2025-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_librovisitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librovisitas',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
