# Generated by Django 5.2.8 on 2025-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_librovisitas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadoumbralcyborg',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
