# Generated by Django 5.2.8 on 2025-12-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_mercadoumbralcyborg_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('pensamiento', models.TextField()),
                ('suspiro', models.TextField()),
                ('foto', models.ImageField(upload_to='seguridad/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
