# Generated by Django 5.2.8 on 2025-12-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seguridad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguridad',
            old_name='pensamiento',
            new_name='santo',
        ),
        migrations.RenameField(
            model_name='seguridad',
            old_name='suspiro',
            new_name='sena',
        ),
        migrations.AddField(
            model_name='bienvenida',
            name='tipo_usuario',
            field=models.CharField(default='Invitado', max_length=50),
        ),
    ]
