# Generated by Django 5.2.8 on 2025-12-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_pensamiento_seguridad_santo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguridad',
            name='foto',
        ),
    ]
