# Generated by Django 5.2.8 on 2025-12-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_seguridad_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='expedientes/'),
        ),
    ]
