# Generated by Django 5.2.8 on 2025-12-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_desktop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Susurro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('seccion', models.CharField(choices=[('paginabase', 'Página Base'), ('autenticacion', 'Autenticación'), ('bienvenida', 'Bienvenida'), ('desktop', 'Desktop'), ('diarios', 'Diarios'), ('movil', 'Móvil'), ('expedientes', 'Expedientes'), ('tablet', 'Tablet'), ('pistas', 'Pistas'), ('laptop', 'Laptop')], max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('susurro', models.TextField()),
                ('activado', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
