# Generated by Django 5.2.8 on 2025-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_susurro'),
    ]

    operations = [
        migrations.AddField(
            model_name='capituloimagen',
            name='es_demo',
            field=models.BooleanField(default=True),
        ),
    ]
