# Generated by Django 5.2.8 on 2025-12-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_capituloimagen_es_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='susurro',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
