# Generated by Django 5.2.8 on 2025-12-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_susurro_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='susurro',
            name='seccion',
            field=models.CharField(choices=[('paginabase', 'Página Base'), ('autenticacion', 'Autenticación'), ('bienvenida', 'Bienvenida'), ('desktop', 'Desktop'), ('diarios', 'Diarios'), ('movil', 'Móvil'), ('expedientes', 'Expedientes'), ('tablet', 'Tablet'), ('pistas', 'Pistas'), ('laptop', 'Laptop'), ('tomos', 'Tomos'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('darkweb', 'Dark Web'), ('cyborgs', 'Cyborgs'), ('ordenes', 'Órdenes'), ('humanas', 'Humanas'), ('linea_temporal', 'Línea Temporal'), ('murales', 'Murales')], max_length=50),
        ),
    ]
