# Generated by Django 5.2.8 on 2025-12-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_susurro_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='es_demo',
            field=models.BooleanField(default=False),
        ),
    ]
