# Generated by Django 5.2.8 on 2026-02-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_capitulo_es_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='susurro',
            name='seccion',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('movil', 'Móvil'), ('diarios', 'Diarios'), ('tablet', 'Tablet'), ('mural', 'Mural'), ('presentacion', 'Presentación'), ('paginabase', 'Página Base'), ('autenticacion', 'Autenticación'), ('bienvenida', 'Bienvenida'), ('expedientes', 'Expedientes'), ('pistas', 'Pistas'), ('tomos', 'Tomos'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('darkweb', 'Dark Web'), ('cyborgs', 'Cyborgs'), ('ordenes', 'Órdenes'), ('humanas', 'Humanas'), ('linea_temporal', 'Línea Temporal')], max_length=50),
        ),
    ]
