# Generated by Django 5.2.8 on 2026-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_capitulo_is_vip_alter_susurro_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='es_demo',
            field=models.BooleanField(default=True),
        ),
    ]
