# Generated by Django 5.2.8 on 2026-02-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_capitulo_es_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('nombre', models.CharField(help_text='Ej: Acceso VIP Marzo o Master Key', max_length=100)),
                ('clave', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('maestra', 'Llave Maestra (Admin)'), ('vip', 'Acceso VIP Temporal'), ('laptop', 'Acceso Laptop Temporal')], default='vip', max_length=10)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clave de Acceso',
                'verbose_name_plural': 'Claves de Acceso',
            },
        ),
    ]
