# Generated by Django 5.2.8 on 2026-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_claveacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='palabras',
            field=models.IntegerField(default=0, help_text='Contador de palabras del capítulo'),
        ),
    ]
