# Generated by Django 5.2.8 on 2026-03-02 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_imagenaibase_promptai'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapituloPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('titulo', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.capitulo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
