# Generated by Django 5.2.8 on 2026-03-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_capituloprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptai',
            name='categoria',
            field=models.CharField(choices=[('perfil-sl', 'Perfil SL'), ('personajes', 'Personajes'), ('bienvenidas', 'Bienvenidas'), ('book-fotos', 'Book de Fotos'), ('utilidades', 'Utilidades'), ('variados', 'Variados'), ('modelo-prompt', 'Modelo de Prompt')], default='variados', max_length=50, verbose_name='Categoría'),
        ),
    ]
