# Generated by Django 5.2.8 on 2026-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_promptai_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pais', models.CharField(default='Unknown', max_length=100, verbose_name='País')),
                ('pais_codigo', models.CharField(default='??', max_length=10, verbose_name='Código País')),
                ('ciudad', models.CharField(default='Unknown', max_length=100, verbose_name='Ciudad')),
                ('ruta', models.CharField(default='/backups', max_length=255)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-created_at'],
            },
        ),
    ]
