# Generated by Django 5.2.8 on 2026-03-13 12:07

import django.db.models.deletion
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    PromptAI = apps.get_model('core', 'PromptAI')
    PromptCategoria = apps.get_model('core', 'PromptCategoria')
    
    for p in PromptAI.objects.all():
        if p.categoria_old:
            # Find or create category
            slug = p.categoria_old
            nombre = slug.replace('-', ' ').title()
            cat, _ = PromptCategoria.objects.get_or_create(nombre=nombre, defaults={'slug': slug})
            p.categoria = cat
            p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_visita'),
    ]

    operations = [
        # 1. Create the model
        migrations.CreateModel(
            name='PromptCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo (borrado lógico)')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Prompt',
                'verbose_name_plural': 'Categorías de Prompts',
            },
        ),
        # 2. Rename existing field to old
        migrations.RenameField(
            model_name='promptai',
            old_name='categoria',
            new_name='categoria_old',
        ),
        # 3. Add the new field as nullable
        migrations.AddField(
            model_name='promptai',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='core.promptcategoria', verbose_name='Categoría'),
        ),
        # 4. Data migration
        migrations.RunPython(migrate_categories),
        # 5. Remove the old field
        migrations.RemoveField(
            model_name='promptai',
            name='categoria_old',
        ),
    ]
