# Generated by Django 5.2.8 on 2026-03-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_promptcategoria_alter_promptai_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='play_voz',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Voz predeterminada para el capítulo (M o F)', max_length=1),
        ),
    ]
