# Generated by Django 5.2.8 on 2026-03-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_capitulo_play_voz'),
    ]

    operations = [
        migrations.AddField(
            model_name='claveacceso',
            name='play_voz',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', help_text='Preferencia de voz (M o F)', max_length=1),
        ),
    ]
